src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraint as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $gender;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="integer")
     */
    private $zip_code;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $dob;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $role;

    /**
     * @ORM\OneToMany(targetEntity=Order::class, mappedBy="user")
     */
    private $orders;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    public function __construct()
    {
        $this->orders = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getZipCode(): ?int
    {
        return $this->zip_code;
    }

    public function setZipCode(int $zip_code): self
    {
        $this->zip_code = $zip_code;

        return $this;
    }

    public function getDob(): ?\DateTimeInterface
    {
        return $this->dob;
    }

    public function setDob(\DateTimeInterface $dob): self
    {
        $this->dob = $dob;

        return $this;
    }

    public function getRole(): ?string
    {
        return $this->role;
    }

    public function setRole(?string $role): self
    {
        $this->role = $role;

        return $this;
    }

    /**
     * @return Collection|Order[]
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders[] = $order;
            $order->setUser($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): self
    {
        if ($this->orders->removeElement($order)) {
            // set the owning side to null (unless already changed)
            if ($order->getUser() === $this) {
                $order->setUser(null);
            }
        }

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }
}

src/Form/ProfilType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;

class ProfilType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('gender', ChoiceType::class,[
                'choices' => [
                    'homme'=>'Homme',
                    'femme'=>'Femme',
            ],
                'required'=>true,
                'multiple'=>false,
                'expanded'=>true,
                'label'=> 'Civilité'
            ])

            ->add('last_name', TextType::class,[
                'required' => true,
                'label'=> 'Nom',           
                'attr' =>[
                'placeholder' => 'Doe'
                 ]

            ] )           
            ->add('first_name', TextType::class,[
                'required' => true,
                'label'=> 'Prénom',
                'attr' =>[
                    'placeholder' => 'John'
                ]
            ])
            ->add('email', EmailType::class, [
                'required' =>true,
                'attr'=>[
                    'placeholder'=> 'prenom.nom@domaine.com'
                ]
            ])
            ->add('address', TextType::class, [
                'required'=>false,
                'label'=> 'Adresse',
                'attr'=>[
                    'placeholder'=> 'Ex: 11 rue de la Liberté'
                ]
            ])
            ->add('city', TextType::class,[
                'required'=>false,
                'label'=> 'Ville',
                'attr'=>[
                    'placeholder'=> 'Ex: Paris'
                ]
            ])
            ->add('zip_code', IntegerType::class, [
                'required'=>false,
                'label'=> 'Code postal',
                'attr'=>[
                    'placeholder'=> 'Ex: 75000',
                    'min'=> 10000,
                    'max'=>99999,
                ]

            ] )
            ->add('dob', BirthdayType::class, [
                'required'=> false,
                'label'=> 'Date de naissance',
                'widget'=> 'single_text',
                'format'=> 'yyyy-MM-dd',
                'attr'=>[
                    'placeholder'=> 'jj-mm-yyyy'
                ]
            ])
            ->add('valider', SubmitType::class)
            
            
        
            
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/ProfilController.php
<?php

namespace App\Controller;

use App\Form\ProfilType;
use App\Repository\UserRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ProfilController extends AbstractController
{
    #[Route('/compte_infos_personnelles', name: 'compte_infos_personnelles')]
    public function index(): Response
    {   
        
        return $this->render('profil/profil.html.twig', [
            'profil' => 'ProfilController',
        ]);
    }
   
    
    
    #[Route('/compte_infos_personnelles/update-{id}', name: 'compte_infos_personnelles_update')]
       
    public function updateCustomer (UserRepository $userRepository, $id, Request $request)
    {
        $customer = $userRepository->find($id);
        $form = $this->createForm(ProfilType::class, $customer);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){

            $manager = $this->getDoctrine()->getManager();
            $manager->persist($customer);
            $manager->flush();

            $this->addFlash('success', 'vos données personnelles ont été bien modifiées');
            return $this->redirectToRoute('compte_infos_personnelles');

        }
        return $this->render('profil/profilForm.html.twig', [
            'profilForm' => $form->createView()
        ]);
    }





}

templates/profil/profil.html.twig
{% extends 'baseClient.html.twig' %}

{% block title %}Hello ProfilController!{% endblock %}

{% block body %}
<div class="text-center  offset-1" >
          <div class="  text-center" id="id-mes-titres-profil">
            <h1>  Bienvenue dans votre espace personnel</h1>
            <h6>Vous pouvez modifier vos informations</6>
          </div>
            
          <div class="col-12 " >
             <img alt="picture" src="{{ asset('images/profil.jpg') }}" class="img-lg rounded-circle border shadow" id=""/>
             <h3>{{app.user.LastName}}</h3>
          </div>
            
          <div class="tab-pane fade show active " id="profile" role="tabpanel" aria-labelledby="profile-tab">Profil
            <table class="table table-hover table-sm table-properties">
              <tr v-show="user.sub">
                <th>Genre</th>
                <td style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis; max-width: 20rem;">{{app.user.gender}}</td>
              </tr>
              <tr v-show="user.firstName">
                <th>Prénom</th>
                <td>{{app.user.FirstName}}</td>
              </tr>
              <tr v-show="user.lastName">
                <th>Nom</th>
                <td>{{app.user.LastName}}</td>
              </tr>
              <tr v-show="user.email">
                <th>Adresse email</th>
                <td>{{app.user.username}}</td>
              </tr>
              <tr v-show="user.adresse">
                <th>Adresse</th>
                <td>{{app.user.address}}</td>
              </tr>
              <tr v-show="user.city">
                <th>Ville</th>
                <td>{{app.user.city}}</td>
              </tr>
              <tr v-show="user.code.postal">
                <th>Code postal</th>
                <td>{{app.user.zipCode}}</td>
              </tr>
              <tr v-show="user.date.anniversaire">
                <th>Date d'anniversaire</th>
                <td>{{app.user.dob.format('d/m/y')}}</td>
              </tr>
              
                
                
              

            </table>
            
            <a href="{{ path('compte_infos_personnelles_update', {'id':app.user.id}) }}" class="btn btn-secondary"><i >Modifier</i></a>
        </div>
              
 </div>
        

{% endblock %}

templates/profil/profilForm.html.twig
{% extends 'base.html.twig' %}

{% block title%} Utilisateur  formulaire {% endblock %}

{% block body %}
   
    <h1 class="text-center" id="id-h1-form"> Formulaire - de données personnelles </h1>
   
    <div class="container-fluid " id="id-main-page-contact">
    {{ form_start(profilForm) }}
    
        <div class="row">
           
            <div class="col-2 offset-2 mb-3 text-secondary " >
                {{  form_label(profilForm.gender) }}
                {{ form_widget(profilForm.gender) }}
               
            </div>

            <div class="col-2 mb-3 text-secondary" >
                {{ form_label(profilForm.last_name) }}
                {{ form_widget(profilForm.last_name) }}
            </div>

            <div class="col-2 mb-3 text-secondary" >
                {{ form_label(profilForm.first_name) }}
                {{ form_widget(profilForm.first_name) }}
            </div>


            <div class="col-8 offset-2 mb-3 text-secondary">
                {{ form_label(profilForm.email) }}
                {{ form_widget(profilForm.email) }}
            </div>

            <div class="col-8 offset-2 mb-3 text-secondary">
                {{ form_label(profilForm.address) }}
                {{ form_widget(profilForm.address) }}
            </div>

            <div class="col-8 offset-2 mb-3 text-secondary">
                {{ form_label(profilForm.city) }}
                {{ form_widget(profilForm.city) }}
            </div>

            <div class="col-8 offset-2 mb-3 text-secondary">
                {{ form_label(profilForm.zip_code) }}
                {{ form_widget(profilForm.zip_code) }}
            </div>
            <div class="col-8 offset-2 mb-3 text-secondary">
                {{ form_label(profilForm.dob) }}
                {{ form_widget(profilForm.dob) }}
            </div>
            <br>
            <div class="col-8 offset-2 text-center mb-3  " >
                {{ form_widget(profilForm.valider) }}
            </div>
            <div class="text-center mb-3">
                <a href="{{ path('compte_infos_personnelles')}}" class="btn btn-secondary"> Annuler </a>
              </div>

        </div>

    {{ form_end(profilForm) }}
    
    </div>

  
   

{% endblock %}